services:
  app:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
    network_mode: service:db
    volumes:
      - ../..:/workspaces:cached
    depends_on:
      db:
        condition: service_healthy
    command: sleep infinity

  db:
    image: postgres:17
    networks:
      - postgres-project-network
    restart: unless-stopped
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./init-databases.sh:/docker-entrypoint-initdb.d/init-databases.sh
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_MULTIPLE_DATABASES: postgres_project,keycloak,temporal
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  customer-db:
    image: postgres:17
    networks:
      - postgres-project-network
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5433:5432"
    command: ['postgres', '-c', 'config_file=/etc/postgresql/postgresql.conf']
    volumes:
      - ../data/customer-db:/var/lib/postgresql/data
      - ../services/test-env/docker/postgres.conf:/etc/postgresql/postgresql.conf
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d postgres -p 5432"]
      interval: 5s
      timeout: 5s
      retries: 5
    depends_on:
      db:
        condition: service_healthy

  keycloak:
    image: quay.io/keycloak/keycloak:22.0.0
    command: start-dev
    networks:
      - postgres-project-network
    ports:
      - "8080:8080"
    environment:
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://db:5432/keycloak
      KC_DB_USERNAME: postgres
      KC_DB_PASSWORD: postgres
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    depends_on:
      db:
        condition: service_healthy

  temporal:
    image: temporalio/auto-setup:1.22.3
    networks:
      - postgres-project-network
    ports:
      - "7233:7233"
    volumes:
      - ./temporal-config.yaml:/etc/temporal/config/dynamicconfig/development.yaml
    environment:
      - DYNAMIC_CONFIG_FILE_PATH=/etc/temporal/config/dynamicconfig/development.yaml
      - DB=postgresql
      - DB_PORT=5432
      - POSTGRES_USER=postgres
      - POSTGRES_PWD=postgres
      - POSTGRES_SEEDS=db
      - POSTGRES_DB=temporal
      - AUTO_SETUP=true
      - TEMPORAL_CREATE_DEFAULT_NAMESPACE=true
      - TEMPORAL_NAMESPACE_RETENTION=30d
      - DEFAULT_NAMESPACE_RETENTION=30d
    depends_on:
      db:
        condition: service_healthy

  temporal-ui:
    image: temporalio/ui:2.22.3
    networks:
      - postgres-project-network
    ports:
      - "8088:8080"
    environment:
      - TEMPORAL_ADDRESS=temporal:7233
    depends_on:
      - temporal

  influxdb:
    image: influxdb:2
    networks:
      - postgres-project-network
    restart: unless-stopped
    ports:
      - "8086:8086"
    volumes:
      - influxdb-data:/var/lib/influxdb2
      - influxdb-config:/etc/influxdb2
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=admin
      - DOCKER_INFLUXDB_INIT_PASSWORD=password
      - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=my-super-secret-admin-token
      - DOCKER_INFLUXDB_INIT_ORG=postgres-project
      - DOCKER_INFLUXDB_INIT_BUCKET=my-bucket

networks:
  postgres-project-network:
    driver: bridge

volumes:
  postgres-data:
  influxdb-data:
  influxdb-config:
